---

- name: Run Linux role to configure a Linux workstation
  ansible.builtin.include_role:
    name: linux
  tags: linux

- name: Run tuned role to configure tuned profile workstation
  ansible.builtin.include_role:
    name: tuned
  tags: tuned

- name: Clone dotfiles repo and stow configs
  ansible.builtin.include_role:
    name: dotfiles
  tags: dotfiles

- name: Run bash role to configure bash
  ansible.builtin.include_role:
    name: bash
  tags: bash

- name: Run Homebrew role to install and configure Homebrew
  ansible.builtin.include_role:
    name: homebrew
  tags: homebrew

- name: Run tmux role to configure tmux
  ansible.builtin.include_role:
    name: tmux
  tags: tmux
