---

- name: Clone dotfiles repo
  ansible.builtin.include_role:
    name: dotfiles

- name: Run MacOS role to configure a MacOS workstation
  ansible.builtin.include_role:
    name: macos

- name: Install and configure macports
  ansible.builtin.include_role:
    name: macports

- name: Run Homebrew role to install and configure Homebrew
  ansible.builtin.include_role:
    name: homebrew

- name: Run NeoVim role to configure Neovim
  ansible.builtin.include_role:
    name: neovim

- name: Run tmux role to configure tmux
  ansible.builtin.include_role:
    name: tmux

- name: Run zsh role to configure zsh
  ansible.builtin.include_role:
    name: zsh

- name: Run alacritty role to configure alacritty
  ansible.builtin.include_role:
    name: alacritty
