---

- name: Install and configure macports
  ansible.builtin.include_role:
    name: macports
  tags: macports

- name: Run Homebrew role to install and configure Homebrew
  ansible.builtin.include_role:
    name: homebrew
  tags: homebrew

- name: Run zsh role to configure zsh
  ansible.builtin.include_role:
    name: zsh
  tags: zsh

- name: Clone dotfiles repo
  ansible.builtin.include_role:
    name: dotfiles

- name: Run MacOS role to configure a MacOS workstation
  ansible.builtin.include_role:
    name: macos
  tags: macos

- name: Run tmux role to configure tmux
  ansible.builtin.include_role:
    name: tmux
  tags: tmux
