- name: Run MacOS role to configure a MacOS workstation
  ansible.builtin.include_role:
    name: MacOS

- name: Run Homebrew role to install and configure Homebrew
  ansible.builtin.include_role:
    name: Homebrew

- name: Run NeoVim role to configure Neovim
  ansible.builtin.include_role:
    name: NeoVim
