---
- name: Configure my workstation right after installation
  hosts: all
  become: false
  become_user: root

  tasks:
    - name: Download dotfiles
      ansible.builtin.git:
        repo: "git@gitlab.com:vorbster/dotfiles.git"
        dest: /tmp/dotfiles
        force: true
        version: master

    - name: Configure Linux hosts
      ansible.builtin.include_tasks: "linux.yml"
      when: ansible_system == "Linux"
      vars:
        my_user: "vorb"
        my_group: "vorb" 

    - name: Configure MacOS hosts
      ansible.builtin.include_tasks: "macos.yml"
      when: ansible_system == "Darwin"
      vars:
        my_user: "vorb"
        my_group: "staff" 
