---

- name: Download dotfiles
  ansible.builtin.git:
    repo: "git@github.com:vorbster/dotfiles.git"
    dest: "{{ ansible_user_dir }}/dotfiles"
    force: true
    version: master
  environment:
    GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

- name: Make sure .config exists as a directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: '0755'

- name: Make sure .local/share exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share"
    state: directory
    mode: '0755'

- name: Pre-create a directory for tmux plugins
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.tmux/plugins"
    state: directory
    mode: '0755'

- name: Make sure zsh config does not exist as a file
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.zshrc"
    state: absent

- name: Stow dotfiles
  ansible.builtin.command: stow "{{ item }}"
  args:
    chdir: "{{ ansible_user_dir }}/dotfiles"
  environment:
    PATH: "{{ ansible_env.PATH }}:/opt/local/bin"
  loop: "{{ dotfiles_stow }}"
  changed_when: false
