---

- name: Download dotfiles
  ansible.builtin.git:
    repo: "git@gitlab.com:vorbster/dotfiles.git"
    dest: "{{ ansible_user_dir }}/dotfiles"
    force: true
    version: main

- name: Make sure .config exists as a directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: '0755'

- name: Make sure .local/share exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share"
    state: directory
    mode: '0755'

- name: Pre-create a directory for tmux plugins
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.tmux/plugins"
    state: directory
    mode: '0755'
