---
- name: Create directory for key bindings
  ansible.builtin.file:
    path: "~/Library/KeyBindings"
    state: directory
    owner: "{{ my_user }}"
    group: "{{ my_group }}"
    mode: "{{ 0644}}"

- name: Install Key Bindings file
  ansible.builtin.copy:
    src: DefaultKeyBinding.dict
    dest: "~/Library/KeyBindings/"
    owner: "{{ my_user }}"
    group: "{{ my_group }}"
    mode: "0644"

- name: Configure defaults
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ macos_defaults }}"
