---
- name: Create directory for key bindings
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Library/KeyBindings"
    state: directory
    mode: '0644'

- name: Install Key Bindings file
  ansible.builtin.copy:
    src: DefaultKeyBinding.dict
    dest: "{{ ansible_user_dir }}/Library/KeyBindings/"
    mode: '0644'

- name: Configure defaults
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ macos_defaults }}"
