- name: Check if oh my zsh is already installed
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: ohmyzsh_dir

- name: Install oh my zsh
  block:
    - name: Download oh my zsh installer
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
        dest: /tmp/install.sh

    - name: Install Oh my zsh
      shell: /tmp/install.sh --unattended
  when: not ohmyzsh_dir.stat.exists

- name: Get zsh location
  shell: "which zsh"
  register: zsh_bin

- name: Change default shell to zsh
  become: true
  user:
    name: "{{ MY_USER }}"
    shell: "{{ zsh_bin.stdout }}"

- name: Copy zsh config
  ansible.builtin.copy:
    src: "/tmp/dotfiles/zsh/zshrc"
    dest: "~/.zshrc"
    remote_src: true

- name: Link a p10k config
  ansible.builtin.copy:
    src: "/tmp/dotfiles/zsh/p10k.zsh"
    dest: "~/.p10k.zsh"
    remote_src: true

- name: Clone powerlevel10k repo
  ansible.builtin.git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k/"
    force: yes

- name: Clone fzf-git 
  ansible.builtin.git:
   repo: "https://github.com/junegunn/fzf-git.sh.git"
   dest: "/tmp/fzf-git"

- name: Copy fzf-git script to /usr/local/bin
  ansible.builtin.copy:
   src: "/tmp/fzf-git/fzf-git.sh"
   dest: /usr/local/bin/ 
   remote_src: true
  become: yes

