---

- name: Install Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  environment:
    NONINTERACTIVE: 1 

- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ brew_packages }}"
