- name: Install tmux config file
  ansible.builtin.copy:
    src: "/tmp/dotfiles/tmux.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    owner: "{{ my_user }}"
    group: "{{ my_group }}"
    mode: "0644"
    remote_src: true

- name: Create tmux plugins dir
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.tmux/plugins"
    state: directory
    owner: "{{ my_user }}"
    group: "{{ my_group }}"

- name: Clone tmux plugins git repositories
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.tmux/plugins/{{ item | basename | split('.') | first }}"
    force: true
  loop: "{{ tmux_git_repos }}"

- name: Upload my dracula theme
  ansible.builtin.copy:
    src: "/tmp/dotfiles/tmux-dracula"
    dest: "{{ ansible_user_dir }}/.tmux/plugins" 
    owner: "{{ my_user }}"
    group: "{{ my_group }}" 
    remote_src: true
