---

- name: Create directory for configs
  ansible.builtin.file:
   name: "~/.config/alacritty"
   state: directory
   owner: "{{ MY_USER }}"
   group: "{{ MY_GROUP }}" 

- name: Sync config files for alacritty
  ansible.posix.synchronize:
   src: "/tmp/dotfiles/alacritty"
   dest: "~/.config/" 
