---

- name: Sync config files for alacritty
  ansible.builtin.copy:
    src: "/tmp/dotfiles/alacritty"
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0755"
    remote_src: true

- name: Create directory for configs
  ansible.builtin.file:
    name: "{{ ansible_user_dir }}/.config/alacritty"
    state: directory
    recurse: true
