---

homebrew_packages:
  - neovim
  - mc
  - wget
  - node
  - lua
  - tmux
  - fd
  - fzf
  - bat
  - eza
  - ripgrep
  - ansible
  - ansible-lint
  - lazygit
  - nerdfetch
  - htop
  - rust
  - stow
  - bash

homebrew_packages_mac: []

homebrew_packages_linux: []

homebrew_tap_mac:
  - epk/epk

homebrew_tap_linux: []

homebrew_casks:
  - font-jetbrains-mono-nerd-font
  - font-droid-sans-mono-nerd-font
  - font-sauce-code-pro-nerd-font
  - font-sf-mono-nerd-font

homebrew_casks_linux: []

homebrew_casks_mac:
  - ghostty
  - sanesidebuttons
  - gimp
