- name: Create config directory
  ansible.builtin.file:
    path: "~/.config"
    state: directory
    owner: "{{ MY_USER }}"
    group: "{{ MY_GROUP }}"

- name: Sync neovim configs from dotfiles
  ansible.builtin.shell: "rsync -avu --delete /tmp/dotfiles/nvim ~/.config"
