- name: Create config directory
  ansible.builtin.file:
    path: "{{ MY_USER }}/.config"
    state: directory
    owner: "{{ MY_USER }}"
    group: "{{ MY_GROUP }}"

- name: Sync neovim configs from dotfiles
  ansible.posix.synchronize:
   src: "/tmp/dotfiles/nvim"
   dest: "{{ MY_USER }}/.config/" 
   owner: "{{ MY_USER }}" 
   groul: "{{ MY_GROUP }}" 
