- name: Create config directory
  ansible.builtin.file:
    path: "~/.config"
    state: directory
    owner: "{{ MY_USER }}"
    group: "{{ MY_GROUP }}"

- name: Sync neovim configs from dotfiles
  ansible.posix.synchronize:
   src: "/tmp/dotfiles/nvim"
   dest: "~/.config/" 
   delete: yes 
