- name: Create config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: "0700"

- name: Sync neovim configs from dotfiles
  ansible.builtin.command: "rsync -avu --delete /tmp/dotfiles/nvim {{ my_home }}/.config"
  changed_when: false
