- name: Create config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory

- name: Pull neovim config git repo
  ansible.builtin.git:
    repo: "{{ nvim_git }}"
    dest: "{{ ansible_user_dir }}/.config/neovim"
