- name: Symlink tmux config file
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.config/nvim/tmux.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    state: link

- name: Create tmux plugins dir
  file:
    path: "{{ ansible_user_dir }}/.tmux/plugins"
    state: directory

- name: Clone tmux plugins git repositories
  git:
    repo: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.tmux/plugins/"
    force: true
  loop: "{{ tmux_git_repos }}"
